// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Hardcoded Supabase credentials for project eubrvlzkvzevidivsfha
export const SUPABASE_URL = 'https://eubrvlzkvzevidivsfha.supabase.co';
export const SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_NlYHzHOT9LzEHgNuNfk_Ag_JBvPUWKF';

console.log('✅ Supabase client initializing with URL:', SUPABASE_URL.substring(0, 30) + '...');

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Safely get localStorage only if in browser environment
const getStorage = () => {
  if (typeof window !== 'undefined' && typeof window.localStorage !== 'undefined') {
    return window.localStorage;
  }
  return undefined;
};

// NOTE: The auto-generated `Database` types only cover a subset of the live schema
// (tables like boqs, lcl_template_*, cash_receipts are missing). To unblock the
// build while the types regenerate, the client is cast to `any` here. Runtime
// behaviour is unchanged.
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: getStorage(),
    storageKey: 'sb-auth-token',
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  global: {
    headers: {
      'x-client-info': 'supabase-js/web',
    },
  },
}) as any;
