// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables for Supabase credentials
export const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://klifzjcfnlaxminytmyh.supabase.co';
export const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsaWZ6amNmbmxheG1pbnl0bXloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2ODg5NzcsImV4cCI6MjA3MTI2NDk3N30.kY9eVUh2hKZvOgixYTwggsznN4gD1ktNX4phXQ5TTdU';

console.log('✅ [Supabase] Client initializing');
console.log('📍 [Supabase] URL:', SUPABASE_URL);
console.log('🔑 [Supabase] Using environment variables:', {
  hasUrl: !!import.meta.env.VITE_SUPABASE_URL,
  hasKey: !!import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,
  env: import.meta.env.MODE
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Safely get localStorage only if in browser environment
const getStorage = () => {
  if (typeof window !== 'undefined' && typeof window.localStorage !== 'undefined') {
    try {
      // Test if localStorage is accessible by trying to set/get/remove a test key
      const testKey = '__storage_test__';
      window.localStorage.setItem(testKey, 'test');
      window.localStorage.removeItem(testKey);
      console.log('✅ [Supabase] localStorage is available and accessible');
      return window.localStorage;
    } catch (e) {
      console.warn('⚠️ [Supabase] localStorage is blocked or unavailable:', e instanceof Error ? e.message : String(e));
      return undefined;
    }
  }
  console.warn('⚠️ [Supabase] Not in browser environment or localStorage not available');
  return undefined;
};

// NOTE: The auto-generated `Database` types only cover a subset of the live schema
// (tables like boqs, lcl_template_*, cash_receipts are missing). To unblock the
// build while the types regenerate, the client is cast to `any` here. Runtime
// behaviour is unchanged.
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: getStorage(),
    storageKey: 'sb-auth-token',
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  global: {
    headers: {
      'x-client-info': 'supabase-js/web',
    },
  },
}) as any;
